title: "Dr. Aman Abidi"

# Shown in the header under your name. HTML is allowed.
description: |
  Research Fellow, National Institute of Education (NIE), Nanyang Technological University (NTU), Singapore<br>
  <strong>Email:</strong> <a href="mailto:aman.abidi@nie.edu.sg">aman.abidi@nie.edu.sg</a> &middot;
  <a href="mailto:aman.abidi@gmail.com">aman.abidi@gmail.com</a><br>
  <a href="https://scholar.google.com/citations?user=CoLi5Q8AAAAJ&hl=en">Google Scholar</a> &middot;
  <a href="https://orcid.org/0000-0002-3960-6259">ORCID</a> &middot;
  <a href="https://github.com/amanabidi">GitHub</a> &middot;
  <a href="https://www.linkedin.com/in/amanabidi/">LinkedIn</a>

# Shows the headshot in the header
logo: /assets/Image/Hawthorn Park.jpg
